name: CICD Pipeline


on: 
  push:
         branches:
            - dev
  pull_request:
    branches:
         - main

jobs:
  build:
    runs-on: self-hosted
    #runs-on: ubuntu-latest

    defaults:
          run:
           shell: cmd
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # - name: Setup .NET
      #   uses: actions/setup-dotnet@v4
      #   with:
      #     dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal

      - name: Publish
        run: dotnet publish --configuration Release --no-build --output ./publish


      # Stop IIS App Pool
      # - name: Stop App Pool
      #   run: |
      #     %windir%\system32\inetsrv\appcmd stop apppool /apppool.name:"TestCICDAppPool"

      # ✅ NEW STEP – copy publish output to your local folder      
      - name: copy to local folder
        run: |
          if not exist "F:\Publish code\TestCICD" mkdir "F:\Publish code\TestCICD"
          xcopy  "publish\*" "F:\Publish code\TestCICD\" /E /I /Y
      
      # Start IIS App Pool
      # - name: Start App Pool
      #   run: |
      #      %windir%\system32\inetsrv\appcmd start apppool /apppool.name:"TestCICDAppPool"

      # Start App
      - name : Start Application from Local Folder
        run: | 
           start "" dotnet "F:\Publish code\TestCICD\AppCICD.dll"
      
     # Wait for app startup
      - name: Wait for App
        run: ping 127.0.0.1 -n 11 >nul


      # Verify App is running
      - name  : Verify Application is Running
        run: |
          tasklist | findstr /I "dotnet.exe" >nul
          if errorlevel 1 (echo Application is not running exit 1) else ( echo Application is running)


      # Health check
      - name: Health Check
        run: |
          curl -f http://localhost:5000/health >nul 2>&1 if errorlevel 1 (echo Health check failed
          exit 1) else (echo Health check passed)

       # Failure Summery 
      - name: Failure Summary
        if: failure()
        run: |
         echo "Pipeline Failed"
         echo "Workflow : ${{ github.workflow }}"
         echo "Job : ${{ github.job }}"
         echo "The build or tests have failed. Please check the logs for details."

       # Archive production artifacts      
      - name: Archive Production Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: production-artifacts
          path: ./publish
     
